#! /usr/bin/env bash
# This script send a file from client to server
if [ "$#" -gt 3 ]; then
    echo "$1, $2, $3, $4"
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
else
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
