#!/usr/bin/env bash
# This script configures a ubuntu machine
#sudo apt-get update
sudo apt-get install nginx -y
#sudo chmod -R $USER:$USER /var/www/
#sudo chmod -R $USER:$USER /var/www/html/
sudo touch /var/www/html/index.html
echo "Holberton School" > index.html
sudo mv index.html /var/www/html/index.html
sudo service nginx start
