#!/usr/bin/env bash
# This script configures a ubuntu machine
sudo apt-get install nginx -y
sudo chmod -R 755 /var/www/html
echo "Holberton School" > index.html
#sudo mv index.html /var/www/html/index.nginx-debian.html
