#!/usr/bin/env bash
# This script fix nginx default to listen on port 80
sed -i "s/listen 8080 default_server;/listen 80;/" /etc/nginx/sites-enabled/default
sed -i "s/listen \[::\]:8080 default_server ipv6only=on;//" /etc/nginx/sites-enabled/default
sudo service nginx restart
