#!/usr/bin/env bash
# This script is displaying info about a file

pr="holbertonschool"
if [[ -e $pr ]]; then
    echo "holbertonschool file exists"
    if [[ -s $pr ]]; then
	echo "holbertonschool file is not empty"
    else
	echo "holbertonschool file is empty"
    fi
    if [[ -f $pr ]]; then
	echo "holbertonschool is a regular file"
    fi

else
    echo "holbertonschool file does not exist"

fi
