#!/usr/bin/env bash 
#this script add permissions to modify nginx.conf and add user for nginx process
chmod 666 /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-available/default
pkill -9 apache2
sudo -su "nginx" service nginx restart
